### ISSUE TITLE
Choose CD/CI

### ISSUE THREAD

**Issue by janishorsts** [expect-digital/translate#6]
Two options are available:
* Github Actions
* Drone CI

In general, we use Drone CI for all projects. Why choose Github Actions?

**Comment by VladislavsPerkanuks** [comment]
Imo, I would choose Drone as it more versatile (as in supports github,gitlab ...), while Actions are only in Github. Also there is no need to learn new syntax ¯\_(ツ)_/¯

**Comment by janishorsts** [comment]
True. We can run stuff in Drone CI instantly.

Sometimes it's great to look at alternatives, and try them out. It expands our experience and knowledge background. Actions is easy to use. Besides, we use earthly to automate processes that can be "easily" executed in any CD/CI.

**Comment by VladislavsPerkanuks** [comment]
From the the other hand, maybe you right, as it is more as a test project, we could try Actions just to gain experience. And it then end of this project we could choose, the "best" CD/CI for our other projects, based on knowledge we gained.

**Comment by janishorsts** [comment]
It's hard to beat Drone CI or Concourse CI, but it depends on a project's requirements
